config/routes.rb
Rails.application.routes.draw do
  get 'new' => 'employee_details#new'

  root to: "organisation#home"

  get 'table' => 'organisation#table'

  get 'list' => 'organisation#list'

  get 'tree' => 'organisation#tree'

  resources :employee_details

  

end

app/models/employee_detail.rb
class EmployeeDetail < ActiveRecord::Base
	validates :name, presence: true, uniqueness: { case_sensitive: false }
	validates :designation, presence: true
	belongs_to :manager, :class_name => "EmployeeDetail", :foreign_key => "manager_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employee_details_controller.rb
class EmployeeDetailsController < ApplicationController
  def new
  	@employee_detail = EmployeeDetail.new
    @employee = EmployeeDetail.all
  end

  def create
  	#@emp = EmployeeDetail.new(params[:emp])
  	@employee_detail = EmployeeDetail.new(emp_params)
  	if @employee_detail.save
  		flash[:success] = "Employee added successfully"
      redirect_to table_url
  		
  	else
  		render 'new'
  	end
  end

  def show
    @employee_detail = EmployeeDetail.find(params[:id])
   
  end

  def edit
    @employee_detail = EmployeeDetail.find(params[:id])
    @employee = EmployeeDetail.all
  end

  def update
     @employee_detail = EmployeeDetail.find(params[:id])
     @employee = EmployeeDetail.all
     #@manager = EmployeeDetail.find_by(manager_id: @employee)
     if @employee_detail.update_attributes(emp_params)
     # @manager.update_attributes(manager_params)
      flash[:success] = "Updated Successfully"
      redirect_to @employee_detail
     else
      render 'edit'
    end
  end


  private

  	def emp_params
  			params.require(:employee_detail).permit(:name, :designation, :manager_id)
  	end
    def manager_params
      params.require(:employee_detail).permit(:manager_id)
    end

end

app/controllers/organisation_controller.rb
class OrganisationController < ApplicationController
  def home
  end

  def table
  	@employee = EmployeeDetail.all
  end

  def list
  	@employee = EmployeeDetail.all
  end

  def tree
  	@employee = EmployeeDetail.all
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_details_helper.rb
module EmployeeDetailsHelper
end

app/helpers/organisation_helper.rb
module OrganisationHelper
end

app/views/employee_details/edit.html.erb
<% provide(:title,"Edit") %>
<h1>Edit employee detail</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
	<%= form_for(@employee_detail) do |f| %>
	<%= f.label :name, "Name : " %>
	<%= f.text_field :name %>	
	<%= f.label :designation, "  Designation : " %>
	<%= f.text_field :designation %>
	<% if @employee_detail.manager_id.blank? %>
	<% else %>	
	<%= f.label :manager_id, "  Reporting Manager : " %>	
	<%= f.collection_select(:manager_id, @employee,:id,:name) %>
	<% end %>	
	<%= f.submit "Save Changes", class: "btn btn-primary" %>
	<% end %>
	</div>
</div>

app/views/employee_details/new.html.erb
<% provide(:title,"New") %>
<h1>Add employee detail</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
	<%= form_for(@employee_detail) do |f| %>
	<%= f.label :name, "Name : " %>
	<%= f.text_field :name %>	
	<%= f.label :designation, "  Designation : " %>
	<%= f.text_field :designation %>	
	<%= f.label :manager_id, "  Reporting Manager : " %>	
	<%= f.collection_select(:manager_id, @employee,:id,:name) %>	
	<%= f.submit "Add Employee", class: "btn btn-primary" %>
	<% end %>
	</div>
</div>

app/views/employee_details/show.html.erb
<% provide(:title, @employee_detail.name) %>
<div class="col-md-2 col-md-offset-10">                
 	<%= link_to "Edit", edit_employee_detail_path(@employee_detail), class: "btn btn-block btn-primary" %>
</div>
<div class="center">
<h1><%= @employee_detail.name.upcase %></h1>
<div class="row gap30">
<div class="col-md-6 text-right">Name : </div><div class="text-left"><strong><%= @employee_detail.name %></strong></div>
</div>
<div class="row gap30">
<div class="col-md-6 text-right">Designation : </div><div class="text-left"><strong><%= @employee_detail.designation %></strong></div>
</div>
<div class="row gap30">
<div class="col-md-6 text-right">Manager : </div><div class="text-left">
    <% if @employee_detail.manager_id %>
	<% @manager_name = @employee_detail.manager.name  %>
	<% else %>
	<% @manager_name = nil %>
	<% end %>
	<strong><%= @manager_name %></strong></div>	
</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.nineleaps.com/">Nineleaps Technology Solutions</a>
     - <a href="http://sample.nineleaps.com/">Coding Challenge.</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "ACME Ltd", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Table",   table_path %></li>
            <li><%= link_to "List", list_path %></li>
            <li><%= link_to "Tree", tree_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | ACME Ltd Organization Hierarchy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js"></script> 
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
</body>
</html>

app/views/organisation/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>ACME Ltd - Organisation hierarchy</h1>

  <h2>
    Please select from following views.
  </h2>
	<div class="center jumbotron">
  		<div class="col-md-3">                
 			<%= link_to "Table", table_path, class: "btn btn-block btn-lg btn-primary" %>
  		</div>
  		<div class="col-md-3 col-md-offset-1">                
 			<%= link_to "List", list_path, class: "btn btn-block btn-lg btn-primary" %>
 		</div>
 		<div class="col-md-3 col-md-offset-1">                
 			<%= link_to "Tree", tree_path, class: "btn btn-block btn-lg btn-primary" %>
  		</div> 
  	</div>
</div>

app/views/organisation/list.html.erb
<% provide(:title, "List") %>
<div class="col-md-2 col-md-offset-10">                
 			<%= link_to "Add new", new_url, class: "btn btn-block btn-primary" %>
  		</div>
<h1>List View</h1>
<% @employee.each do |e| %>
<div class="row gap40">
	<% if e.manager_id.blank? %>
		<ul style="list-style-type:disc;">
			<li><strong class="list"><%= link_to e.name,e,title: e.designation %></strong> <small><%= e.designation %></small>	
		
		<% def listing(id) %>
			<ul>
			<% @employee.each do |f| %>	
				<%if f.manager_id == id %>					
						<li><strong class="list"><%= link_to f.name,f,title: f.designation %></strong> <small><%= f.designation %></small>
						<% listing(f.id) %>
						</li>									
				 <% end %>
			<% end%>
			</ul>
		<% end %>
		<% listing(e.id) %>	
			</li>
		</ul>		
	<% end %>
</div>
<% end %>

app/views/organisation/table.html.erb
<% provide(:title, "Table") %>
<div class="col-md-2 col-md-offset-10">                
 			<%= link_to "Add new", new_url, class: "btn btn-block btn-primary" %>
</div>
 <div class="center">
<h1>Employee Details</h1>
<table class="table table-hover">
<thead>
	<tr class="text-left">
		<th>Emp ID</th>
		<th>Name</th>
		<th>Designation</th>
		<th>Manager</th>
	</tr>
	</thead>
	<% @employee.each do |e| %>
	<% if e.manager_id %>
	<% @manager_name = e.manager.name %>
	<% else %>
	<% @manager_name = nil %>
	<% end %>
	<tbody>
	<tr class="text-left">
		<td><%= e.id %> </td>
		<td><%= link_to e.name,e %> </td>
		<td><%= e.designation %> </td>
		<td><%= @manager_name %> </td>
	</tr>
	<% end %>
	</tbody>
</table>
</div>

app/views/organisation/tree.html.erb
<% provide(:title, "Tree") %>
<div class="col-md-2 col-md-offset-10">                
 			<%= link_to "Add new", new_url, class: "btn btn-block btn-primary" %></div>  		
<h1>Tree View</h1>
<div class="row gap40">
<div id="treechart">
</div>
</div>
<% @employee.each do |e| %>
	<% if e.manager_id.blank? %>
		<ul id="org" style="display:none">
			<li><strong class="list"><%= link_to e.name,e,title: e.designation %></strong> <small><%= e.designation %></small>	
		
		<% def listing(id) %>
			<ul>
			<% @employee.each do |f| %>	
				<%if f.manager_id == id %>					
						<li><strong class="list"><%= link_to f.name,f,title: f.designation %></strong> <small><%= f.designation %></small>
						<% listing(f.id) %>
						</li>									
				 <% end %>
			<% end%>
			</ul>
		<% end %>
		<% listing(e.id) %>
			</li>
		</ul>		
	<% end %>
<% end %>

<script>
jQuery(document).ready(function() { $("#org").jOrgChart({chartElement: '#treechart'}); });
</script>

	